server:
  port: 8086

spring:
  application:
    name: notification-service
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 5871f0faaa9e28
    password: fa3d9fb37cffac
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  vapid:
    public-key: BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuBkr3qLOWI-M2X8eF6RStTMI0
    private-key: Yw-H8L-zQ0RjZ4Yg5z1dJw2y4z9Wf6FhA4G_2G9w2qE
    subject: mailto:admin@accounting.com
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
